dist: xenial
sudo: required
language: python
services:
- postgresql
addons:
  postgresql: '10'
cache:
  pip: true
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
jobs:
  include:
  - stage: deploy
    if: tag IS present
    python: 3.8
    script: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-auditlog/upload
      distributions: sdist bdist_wheel
      password:
        secure: AD22a73v//OXpP8WgFscTQHQxpNE5Rup9+NhoxNRNYXszc+g9Z9yNO5cokPHD0HUL7pma/V31xK1tavFO7jHfvidcnx8mNwezoW7lQctNErxhtuAUN59654IaTPmTOU6vvdslmtNT1W/M/LDsp5hWyzaCbTNbl5Ag4+spUpSCq8=
      skip_existing: true
      on:
        tags: true
        repo: jazzband/django-auditlog
  fast_finish: true
install:
  - travis_retry pip install -U pip
  - travis_retry pip install tox-travis codecov
script: tox -v
after_success:
- codecov
